version: '3'

services:
  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    user: root  # 이 줄을 추가합니다.
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    volumes:
      - /mnt/nvme/dataset/spark:/mnt/nvme/dataset/spark

  spark-worker-1:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-1
    user: root  # 이 줄을 추가합니다.
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - /mnt/nvme/dataset/spark:/mnt/nvme/dataset/spark

  spark-worker-2:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-2
    user: root  # 이 줄을 추가합니다.
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - /mnt/nvme/dataset/spark:/mnt/nvme/dataset/spark

  spark-worker-3:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-3
    user: root  # 이 줄을 추가합니다.
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - /mnt/nvme/dataset/spark:/mnt/nvme/dataset/spark

  spark-worker-4:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-4
    user: root  # 이 줄을 추가합니다.
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - /mnt/nvme/dataset/spark:/mnt/nvme/dataset/spark

  spark-worker-5:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-5
    user: root  # 이 줄을 추가합니다.
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network
    volumes:
      - /mnt/nvme/dataset/spark:/mnt/nvme/dataset/spark

networks:
  spark-network:
    driver: bridge
